backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads"

collections:
  - name: "setup"
    label: "Setup"
    files:
    - label: "Site Info"
      name: "info"
      format: 'json'
      file: "content/setup/info.json"
      fields:
        - {label: Site Name, name: sitename, widget: string}
        - {label: Site Description, name: sitedescription, widget: string}
    # TODO
        # - label: "About"
    #   name: "about"
    #   format: 'json'
    #   file: "content/setup/about.json"
    #   fields:
    #     - {label: Site Name, name: sitename, widget: string}
    #     - {label: Site Description, name: sitedescription, widget: string}
  
  - name: "work" # Used in routes, e.g., /admin/collections/blog
    label: "Work" # Used in the UI
    identifier_field: title
    folder: "content/work" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    format: 'json'
    sort: "year:desc" # Default is title:asc
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: "Show?", name: "show", widget: "boolean", default: true}
      - { label: 'Description', name: 'description', widget: 'string'}
      - { label: 'Cover', name: 'cover', widget: 'image'}
      - { label: 'Year', name: 'year', widget: 'number'}
      - { label: 'Body', name: 'body', widget: 'markdown', required: false}
      - { label: 'URL', name: 'project_url', widget: 'string', required: false}
      - { label: 'Full width?', name: 'layout', widget: 'boolean', default: false, required: false}
      - label: "Mockups"
        name: "mockups"
        widget: "object"
        fields:
          - { label: 'Mockup1', name: 'mockup1', widget: 'image', required: false}
          - { label: 'Mockup2', name: 'mockup2', widget: 'image', required: false}
          - { label: 'Mockup3', name: 'mockup3', widget: 'image', required: false}
          - { label: 'Mockup4', name: 'mockup4', widget: 'image', required: false}
          - { label: 'Mockup5', name: 'mockup5', widget: 'image', required: false}

  - name: "art" # Used in routes, e.g., /admin/collections/blog
    label: "Art" # Used in the UI
    folder: "content/art" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    format: 'json'
    sort: "date:desc" # Default is title:asc
    fields:
    - {label: "Show?", name: "show", widget: "boolean", default: true}
    - { label: 'Title', name: 'title', widget: 'string'}
    - { label: 'Image', name: 'cover', widget: 'image'}
    - label: 'Category'
      name: 'category'
      widget: 'select'
      options:
      - { label: "Painting", value: "painting" }
      - { label: "Drawing", value: "drawing" }
      - { label: "Photography", value: "photography" }
      - { label: "Instalation", value: "installation" }
    - { label: 'Medium', name: 'medium', widget: 'string', required: false}
    - { label: 'Year', name: 'year', widget: 'number', required: false}
    - { label: 'Buy', name: 'buy_url', widget: 'string', required: false}
    - { label: 'Layout', name: 'layout', widget: 'select', options: ['w-50', 'w-25', 'square'], required: false}